### PR TITLE
Stops Shadow Temple lore prompts from appearing in rando.

### PR DESCRIPTION
**Pull request by leggettc18**
Fixes https://github.com/briaguya-ai/rando-issue-tracker/issues/47

As far as I can tell there are no issues introduced by this.

### CODE REVIEW

**Comment by briaguya0** [comment]
`z_en_wonder` is used all over the place, have you tested that this doesn't break things outside of shadow temple?

talking to the altar at temple of time is an example, but there are a lot more

**Comment by leggettc18** [comment]
Altar and gossip stones all still work. Were the GTG textboxes already skipped before this?

**Comment by leggettc18** [comment]
I have confirmed that GTG text boxes use the same code via breakpoints. If they weren't skipped before this might be a win-win, but I need to dig around and find any other areas where they are used. I can also tighten the if statement so it only skips select textIds but that list might get quite long. Could also determine whether or not to skip with the sceneNum now that I think about it, or even a mix of both. I could make it pretty manageable with a local variable like "randoSkipText" and some switch case statements to set that variable to true or false.

**Comment by leggettc18** [comment]
Ok. I've been digging around and the only text that seems to be skipped that I didn't explicitly intend to skip are the GTG instructions and the carpenter's "Over here, inside this cell" text in the Gerudo Fortress. All of which seem like things we would want skipped in rando anyway. Altar, Gossip Stones, shops, market randomized text, haunted wasteland guide, Saria's Song, guards (castle and gerudo) all seem to work just fine. Can you think of any other major ones that I've missed?

**Comment by leggettc18** [comment]
Fixed so that it only applies to the Shadow Temple, but also allows for some other instances of wonder_talk2 found in other areas to be skipped with only a few lines of code added to the switch case statements in the future.

**Pull request merged**
